name: listdeployments

env:
  serverURL: https://robe-testing-tc.testoctopus.app/

on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
        with:
          version: latest
      
      - name: Setup Variables
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "CHANNEL=Default" >> $GITHUB_ENV
          else
            echo "CHANNEL=Secondary" >> $GITHUB_ENV
          fi          
      - name: list-octopusdeploy-deployments
        run: octo create-release --server=${{ env.serverURL }} --apiKey=${{ secrets.APIKEY }} --project=MyScript --gitcommit $GITHUB_SHA --gitref $GITHUB_REF --channel Default
      - name: Create a release in Octopus Deploy üêô
        uses: OctopusDeploy/create-release-action@v1.0.6
        with:
          api_key: ${{ secrets.APIKEY }}
          project: "MyScript"
          server: ${{ env.serverURL }}
